[versions]
activityKtx = "1.11.0"
agp = "8.13.0"
circularprogressbar = "3.1.0"
coil = "2.7.0"
coilGif = "2.7.0"
core = "3.5.3"
feather = "1.1.1"
fontawesome = "1.1.0"
gson = "2.13.2"
javaWebsocket = "1.6.0"
kotlin = "2.2.20"
#coreKtx = "1.17.0"
#junit = "4.13.2"
#junitVersion = "1.3.0"
#espressoCore = "3.7.0"
appcompat = "1.7.1"
kotlinxCoroutinesAndroid = "1.10.2"
kotlinxSerializationJson = "1.9.0"
ktor = "2.3.12"
lifecycleRuntimeKtx = "2.9.3"
#material = "1.13.0"
constraintlayout = "2.2.1"
materialVersion = "1.13.0"
media3Ui = "1.8.0"
moshi = "1.15.2"
nanohttpd = "2.3.1"
okhttp = "5.1.0"
retrofit = "3.0.0"
roomRuntime = "2.8.0"
roomKtx = "2.8.0"
socketIoClient = "2.1.2"
timber = "5.0.1"
workRuntimeKtx = "2.10.4"
playServicesMlkitFaceDetection = "17.1.0"

[libraries]
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
#androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-lifecycle-process = { module = "androidx.lifecycle:lifecycle-process", version.ref = "lifecycleRuntimeKtx" }
androidx-lifecycle-runtime-ktx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-media3-common = { module = "androidx.media3:media3-common", version.ref = "media3Ui" }
androidx-media3-effect = { module = "androidx.media3:media3-effect", version.ref = "media3Ui" }
androidx-media3-transformer = { module = "androidx.media3:media3-transformer", version.ref = "media3Ui" }
androidx-media3-exoplayer = { module = "androidx.media3:media3-exoplayer", version.ref = "media3Ui" }
androidx-media3-ui = { module = "androidx.media3:media3-ui", version.ref = "media3Ui" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomRuntime" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "roomRuntime" }
androidx-work-runtime-ktx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
circularprogressbar = { module = "com.mikhaellopez:circularprogressbar", version.ref = "circularprogressbar" }
coil-gif = { module = "io.coil-kt:coil-gif", version.ref = "coilGif" }
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coil-svg = { module = "io.coil-kt:coil-svg", version.ref = "coil" }
converter-kotlinx-serialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit" }
converter-moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofit" }
core = { module = "com.google.zxing:core", version.ref = "core" }
feather = { module = "br.com.devsrsouza.compose.icons:feather", version.ref = "feather" }
fontawesome = { module = "br.com.devsrsouza.compose.icons:fontawesome", version.ref = "fontawesome" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
java-websocket = { module = "org.java-websocket:Java-WebSocket", version.ref = "javaWebsocket" }
#junit = { group = "junit", name = "junit", version.ref = "junit" }
#androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
#androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutinesAndroid" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-server-cio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }
ktor-server-content-negotiation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktor-server-core = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
#noinspection SimilarGradleDependency
#material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
#noinspection SimilarGradleDependency
google-material = { group = "com.google.android.material", name = "material", version.ref = "materialVersion" }
moshi = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-kotlin = { module = "com.squareup.moshi:moshi-kotlin", version.ref = "moshi" }
moshi-kotlin-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
nanohttpd = { module = "org.nanohttpd:nanohttpd", version.ref = "nanohttpd" }
nanohttpd-websocket = { module = "org.nanohttpd:nanohttpd-websocket", version.ref = "nanohttpd" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
socket-io-client = { module = "io.socket:socket.io-client", version.ref = "socketIoClient" }
timber = { module = "com.jakewharton.timber:timber", version.ref = "timber" }
play-services-mlkit-face-detection = { group = "com.google.android.gms", name = "play-services-mlkit-face-detection", version.ref = "playServicesMlkitFaceDetection" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

#kotlin-kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
#kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
